version: "2"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - a
            - b
        #volumes_from:
        #    - fpm
        volumes:
            - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        command: [nginx-debug, '-g', 'daemon off;']
    #fpm:
    #    build: infra/fpm/.
    #    volumes:
    #        - ./code:/code
    a:
        image: php:7-fpm
        volumes:
            - ./a/code:/code/a
    b:
        image: php:7-fpm
        volumes:
            - ./b/code:/code/b