version: "2"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - fpm
        volumes_from:
            - fpm
        volumes:
            - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    fpm:
        build: infra/fpm/.
        volumes:
            - ./code:/code